#!/bin/bash

set -e

echo "Building..."
npm run build

echo "Deploying..."

# Config -----------------
REMOTE_BASE="/home/pi/temperature-monitor"
REMOTE_SERVER="pubpi"

# Script  ----------------
RSYNC_FLAGS_UP="-i --compress --recursive --links --update --exclude '*.swp' --exclude '*.swo' --exclude original-assets --exclude .git --exclude assets"
RSYNC_FLAGS_DOWN="-i --recursive --copy-links --update --exclude '*.swp' --exclude '*.swo' --exclude CVS"

# Modify this if the upload script moves relative to the project directory.
PROJECT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd $PROJECT_DIR

# Upload changes.
rsync $RSYNC_FLAGS_UP $PROJECT_DIR/ ${REMOTE_SERVER}:${REMOTE_BASE}
